FROM ghcr.io/kbialek/deye-inverter-mqtt

RUN mkdir /opt/deye_inverter_mqtt/plugins

COPY build/plugins/deye_plugin_prometheus.py /opt/deye_inverter_mqtt/plugins

ENV DEYE_LOGGER_PROTOCOL=tcp
ENV DEYE_DATA_READ_INTERVAL=60
ENV DEYE_PUBLISH_ON_CHANGE=false

ENV MQTT_HOST=127.0.0.1

ENV PLUGINS_DIR=plugins
ENV PLUGINS_ENABLED=deye_plugin_prometheus
ENV LOG_LEVEL=INFO
ENV LOG_STREAM=STDOUT

ENV DEYE_FEATURE_MQTT_PUBLISHER=false
ENV DEYE_FEATURE_TIME_OF_USE=false
ENV DEYE_FEATURE_ACTIVE_POWER_REGULATION=false
ENV DEYE_FEATURE_SET_TIME=false
ENV DEYE_FEATURE_SOLAR_SELL=false
ENV DEYE_FEATURE_WORKMODE=false
ENV DEYE_FEATURE_BATTERY_SETTINGS=false

ENV PLUGIN_PROMETHEUS_INVERTER_NAME=inverter01
ENV PLUGIN_PROMETHEUS_LISTEN_ADDR=0.0.0.0
ENV PLUGIN_PROMETHEUS_LISTEN_PORT=9010

