name: Build

on:
  push:
    branches:
      - master

env:
  PYTHON_VERSION: 3.13

permissions:
  packages: write
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Update badges
        uses: gaelgirodon/ci-badges-action@v1
        with:
          gist-id: 2964adb9760e49d54940d571d30b55fe
          token: ${{ secrets.GIST_TOKEN }}

      - name: Build
        run: make build

      - name: Detect version
        run: |
          echo "VERSION=$(grep '^version =' pyproject.toml | cut -d '"' -f2 | xargs)" >> $GITHUB_ENV

      - name: Release (prepare)
        run: |
          mkdir release
          mkdir release/deye-exporter-$VERSION
          mkdir release/deye-exporter-$VERSION/plugins
          
          cp LICENSE release/deye-exporter-$VERSION
          cp NOTICE release/deye-exporter-$VERSION
          cp README.md release/deye-exporter-$VERSION
          cp build/plugins/*.py release/deye-exporter-$VERSION/plugins
          
          cd release && tar -czvf deye-exporter-$VERSION.tar.gz deye-exporter-$VERSION

      - name: Release
        run: |
          if gh release view v$VERSION > /dev/null 2>&1; then
            echo "Release v$VERSION already exists. Skipping"
          else
            echo "Releasing: v$VERSION"
            
            ls -la deye-exporter-$VERSION/          
            ls -la .
          
            gh release create v$VERSION \
              --repo tarmolehtpuu/deye-exporter \
              --title deye-exporter-$VERSION \
              --generate-notes *.tar.gz
          
            echo "Release $VERSION - DONE"
          fi
        working-directory: release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
